#
# Build and release plugin
#
name: Release plugin

on:
  workflow_dispatch:
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'liberica'
        cache: maven
    - name: Install Atlassin SDK
      run: |
        sudo sh -c 'echo "deb https://packages.atlassian.com/debian/atlassian-sdk-deb/ stable contrib" >>/etc/apt/sources.list'
        wget https://packages.atlassian.com/api/gpg/key/public
        sudo apt-key add public
        sudo apt-get update
        sudo apt-get install atlassian-plugin-sdk
    - name: Show version
      run: atlas-version
    - name: Build package
      run: atlas-package
    - name: Release package
      run: atlas-release
