#
# Build and release plugin
#
name: Release plugin

on:
  release:
    types: [created]

#on:
#  workflow_dispatch:
#    tags:
#      description: 'Test scenario tags'
#      required: false
#      type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'liberica'
          cache: maven
      - uses: actions/atlas
      - name: Show version
        run: atlas-version
