#
# Build and release plugin
#
name: Release plugin

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install JDK
        uses: ./.github/actions/jdk
      - name: Install Atlassin SDK
        uses: ./.github/actions/atlas
      - name: Show version
        run: atlas-version
