#
# Build and release plugin
#
name: Release plugin

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'liberica'
          cache: maven
      - uses: .github/actions/atlas
      - name: Show version
        run: atlas-version
